name: Build

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Buildplate
        uses: actions/checkout@v4
        with:
          repository: koikirin/buildplate

      - name: Check out source
        uses: actions/checkout@v4
        with:
          path: external/hereditas

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install
        run: |
          yarn --no-immutable
          yarn yakumo prepare
          yarn yakumo resolution
          yarn --no-immutable

      - name: Lint
        run: yarn yakumo run hereditas -- lint

  build:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Buildplate
        uses: actions/checkout@v4
        with:
          repository: koikirin/buildplate

      - name: Check out source
        uses: actions/checkout@v4
        with:
          path: external/hereditas

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install
        run: |
          yarn --no-immutable
          yarn yakumo prepare
          yarn yakumo resolution
          yarn --no-immutable

      - name: Build
        run: yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: external/hereditas/lib
