name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[ci skip]')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Check out Buildplate
        uses: actions/checkout@v4
        with:
          repository: koikirin/buildplate

      - name: Check out source
        uses: actions/checkout@v4
        with:
          path: external/hereditas
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - name: Get version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: |
          yarn --no-immutable
          yarn yakumo prepare
          yarn yakumo resolution
          yarn --no-immutable

      - name: Update version
        run: yarn bump hereditas -v ${{ steps.version.outputs.version }}

      - name: Commit version bump
        run: |
          git -C external/hereditas config user.email "github-actions[bot]@users.noreply.github.com"
          git -C external/hereditas config user.name "github-actions[bot]"
          git -C external/hereditas remote set-branches origin main
          git -C external/hereditas fetch origin main:main
          git -C external/hereditas checkout main
          git -C external/hereditas add package.json
          git -C external/hereditas commit -m "bump version ${{ steps.version.outputs.version }}"
          git -C external/hereditas push origin main

      - name: Check visibility
        if: github.event.repository.private == true
        run: yarn config set npmPublishProvenance false

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn pub --debug
